# Generated by Django 4.1.4 on 2023-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_profile_followers_alter_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to="main.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="follows", to="main.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="posts",
            field=models.ManyToManyField(blank=True, to="main.post"),
        ),
    ]
