# Generated by Django 4.1.4 on 2023-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_postreaction_post_post_reactions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="frontend/assets/images"
            ),
        ),
    ]
