# Generated by Django 4.1.4 on 2023-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_comment_created_at_comment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
