# Generated by Django 4.1.4 on 2023-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_profile_followers_remove_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="follow_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_profile",
                to="main.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="main.profile",
            ),
        ),
    ]
