# Generated by Django 4.1.4 on 2023-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_comment_user_alter_follow_follow_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostReaction",
            new_name="Reaction",
        ),
        migrations.AddField(
            model_name="comment",
            name="comments",
            field=models.ManyToManyField(blank=True, to="main.comment"),
        ),
        migrations.AddField(
            model_name="comment",
            name="reactions",
            field=models.ManyToManyField(blank=True, to="main.reaction"),
        ),
    ]
